### ISSUE TITLE
IND_INJERROR_LOADDLL on Windows 10 Version 2004

### ISSUE THREAD

**Issue by AChenny** [m417z/7-Taskbar-Numberer#1] opened 2020-05-31 04:35 UTC
Getting a error "IND_INJERROR_LOADDLL" when starting up taskbar numberer on Windows 10 Version 2004 OS Build 19041.264. GUI will load but the taskbar numbers will not show up.

**Comment by m417z** [comment] 2020-06-13 09:11
Should be fixed in version 9.9.

**Closed as completed by m417z** 2020-06-13 09:11 UTC

**Comment by M-Momtaz** [comment] 2020-08-08 21:53
> Should be fixed in version 9.9.

Still exist, Is version 9.9 released ?

**Comment by m417z** [comment] 2020-08-09 07:55
Yes, it was released when I posted the comment. I believe that's a new incompatibility, caused by update KB4568831 of Windows 10 version 2004. I didn't look at it yet, but I know that this update broke 7+ Taskbar Tweaker.

**Comment by AChenny** [comment] 2020-08-15 21:48
I believe the last update KB4566782 in Windows 10 2004 also broke Taskbar Numberer 7+

**Comment by m417z** [comment] 2020-08-24 11:52
Please try the newly released version 10.2.

**Comment by M-Momtaz** [comment] 2020-08-26 15:22
> Please try the newly released version 10.2.

It working properly, Thanks @m417z
